runtime: go122  # Or go121, depending on your version
instance_class: F1
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 10
env_variables:
  APP_ENV: "production"
  
